version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "11433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
    entrypoint: ["/bin/bash", "-c"]
    command: |
      for i in {1..60}; do
        /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P $$SA_PASSWORD -Q "
        IF DB_ID('catalog') IS NULL CREATE DATABASE catalog; 
        IF DB_ID('inventory') IS NULL CREATE DATABASE inventory;
        USE catalog;
        IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'catalog_user')
        BEGIN
            CREATE LOGIN catalog_user WITH PASSWORD = 'Catalogo123!';
        END
        IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'catalog_user')
        BEGIN
            CREATE USER catalog_user FOR LOGIN catalog_user;
            ALTER ROLE db_owner ADD MEMBER catalog_user;
        END
        " && exit 0;
        sleep 2;
      done;
      exit 1;

  catalog-ms:
    build: ./catalog-ms
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=catalog;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: catalog_user
      SPRING_DATASOURCE_PASSWORD: Catalogo123!
      CATALOG_API_KEY: catalog-secret
    ports: ["8081:8081"]
    depends_on:
      mssql:
        condition: service_healthy
      mssql-init:
        condition: service_started
    restart: always

  inventory-ms:
    build: ./inventory-ms
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=inventory;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: YourStrong!Passw0rd
      PRODUCTS_BASE_URL: http://catalog-ms:8081
      PRODUCTS_API_KEY: catalog-secret
      INVENTORY_API_KEY: inventory-secret
    ports: ["8082:8082"]
    depends_on:
      mssql:
        condition: service_healthy
      mssql-init:
        condition: service_started
      catalog-ms:
        condition: service_started
    restart: always
